### ISSUE TITLE
Actividad 4 Síntesis

### ISSUE THREAD

**Issue by MLR062998** [SistemasTecTlaxiaco/actividad-4-tarea-de-sintesis-de-calidad-MLR062998#1]
[Sisntesis_calidad_de_software.pdf](https://github.com/SistemasTecTlaxiaco/actividad-4-tarea-de-sintesis-de-calidad-MLR062998/files/12704037/Sisntesis_calidad_de_software.pdf)

**Comment by abicoronel** [comment]
Calificación: 20

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
